# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 10:47
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_fio', models.CharField(max_length=45, verbose_name='Клиент(ФИО)')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Телефон клиента(+79881234567)')),
                ('email', models.EmailField(default='nomail@nomail.ru', max_length=254, verbose_name='email клиента')),
                ('raion', multiselectfield.db.fields.MultiSelectField(choices=[('Ахун', 'Ахун'), ('Адлер', 'Адлер'), ('Бытха', 'Бытха'), ('Виноградная', 'Виноградная'), ('Дагомыс', 'Дагомыс'), ('Донская', 'Донская'), ('Донская(Пасечная)', 'Донская(Пасечная)'), ('Донская(Тимерярева)', 'Донская(Тимерярева)'), ('Завокзальный', 'Завокзальный'), ('Заречный', 'Заречный'), ('Клубничная', 'Клубничная'), ('КСМ', 'КСМ'), ('Красная поляна', 'Красная поляна'), ('Кудепста', 'Кудепста'), ('Макаренко', 'Макаренко'), ('Мамайка', 'Мамайка'), ('Мамайский перевал', 'Мамайский перевал'), ('Мацеста', 'Мацеста'), ('Н.Сочи', 'Н.Сочи'), ('Объезная', 'Объезная'), ('Пластунская', 'Пластунская'), ('Приморье', 'Приморье'), ('Раздольное', 'Раздольное'), ('Светлана', 'Светлана'), ('Соболевка', 'Соболевка'), ('Транспортная', 'Транспортная'), ('Фабрициуса', 'Фабрициуса'), ('Хоста', 'Хоста'), ('Центр', 'Центр')], max_length=290, verbose_name='Район:')),
                ('date_sozd', models.DateField(verbose_name='Дата создания:')),
                ('category', models.CharField(choices=[('Квартиры', 'Квартиры'), ('Дома', 'Дома'), ('Участки', 'Участки')], default='Квартиры', max_length=45, verbose_name='Что ищет')),
                ('cel_pokupki', multiselectfield.db.fields.MultiSelectField(choices=[('ПМЖ', 'ПМЖ'), ('Аренда/Для сдачи', 'Аренда/Для сдачи'), ('Инвестирование', 'Инвестирование')], max_length=35, verbose_name='Цель покупки')),
                ('prim', models.TextField(verbose_name='Примечание')),
                ('budg_ot', models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Бюджет от:')),
                ('budg_do', models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Бюджет до:')),
                ('ferst_work', models.TextField(verbose_name='Проделана первичная работа')),
                ('prich_otkaza', models.TextField(verbose_name='Причина первичного отказа работы')),
                ('auth_old', models.CharField(default='none', max_length=85, verbose_name='Автор(Был раньше):')),
                ('st_pub', multiselectfield.db.fields.MultiSelectField(choices=[('Только у себя', 'Только у себя'), ('Видно в отделе', 'Видно в отделе'), ('Видно всем', 'Видно всем')], default='Только у себя', max_length=39, verbose_name='Oпубликовать в:')),
                ('closed', models.BooleanField(default=False, verbose_name='Клиент закрыт')),
                ('otd', models.CharField(default=' ', max_length=45, verbose_name='Отдел')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор:')),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
                'verbose_name': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='doma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_fio', models.CharField(max_length=45, verbose_name='Клиент(ФИО)')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Телефон клиента(+79881234567)')),
                ('date_sozd', models.DateField(auto_now=True, verbose_name='Дата создания:')),
                ('status_obj', models.CharField(choices=[('Опубликован', 'Опубликован'), ('Не опубликован', 'Не опубликован')], max_length=45, verbose_name='Публикация обьекта')),
                ('raion', models.CharField(choices=[('Ахун', 'Ахун'), ('Адлер', 'Адлер'), ('Бытха', 'Бытха'), ('Виноградная', 'Виноградная'), ('Дагомыс', 'Дагомыс'), ('Донская', 'Донская'), ('Донская(Пасечная)', 'Донская(Пасечная)'), ('Донская(Тимерярева)', 'Донская(Тимерярева)'), ('Завокзальный', 'Завокзальный'), ('Заречный', 'Заречный'), ('Клубничная', 'Клубничная'), ('КСМ', 'КСМ'), ('Красная поляна', 'Красная поляна'), ('Кудепста', 'Кудепста'), ('Макаренко', 'Макаренко'), ('Мамайка', 'Мамайка'), ('Мамайский перевал', 'Мамайский перевал'), ('Мацеста', 'Мацеста'), ('Н.Сочи', 'Н.Сочи'), ('Объезная', 'Объезная'), ('Пластунская', 'Пластунская'), ('Приморье', 'Приморье'), ('Раздольное', 'Раздольное'), ('Светлана', 'Светлана'), ('Соболевка', 'Соболевка'), ('Транспортная', 'Транспортная'), ('Фабрициуса', 'Фабрициуса'), ('Хоста', 'Хоста'), ('Центр', 'Центр')], max_length=45, verbose_name='Район:')),
                ('adress', models.CharField(max_length=70, verbose_name='Адрес:')),
                ('type_house', models.CharField(choices=[('Каркастный', 'Каркастный'), ('Монолит', 'Монолит'), ('Кирпич', 'Кирпич')], max_length=55, verbose_name='Тип дома')),
                ('ploshad_doma', models.IntegerField(verbose_name='Площадь дома')),
                ('remont', models.CharField(choices=[('Черновой', 'Черновой'), ('Чистовой', 'Чистовой'), ('Дизайнерский', 'Дизайнерский'), ('Жилой', 'Жилой'), ('Новый', 'Новый')], max_length=55, verbose_name='Ремонт')),
                ('canalizacia', models.CharField(choices=[('ЛОС', 'ЛОС'), ('Септик', 'Септик'), ('Центральная', 'Центральная')], max_length=45, verbose_name='Канализация')),
                ('gaz', models.CharField(choices=[('Нет', 'Нет'), ('Есть', 'Есть'), ('Можно подключить', 'Можно подключить'), ('В процессе подключения', 'В процессе подключения')], max_length=45, verbose_name='Газ')),
                ('svet', models.IntegerField(verbose_name='Свет(квт)')),
                ('voda', models.CharField(choices=[('Скважена', 'Скважена'), ('Центролизованное', 'Центролизованное'), ('Можно подключить', 'Можно подключить')], max_length=45, verbose_name='Водоснабжение')),
                ('komnat', models.IntegerField(verbose_name='Кол-во комнат')),
                ('sotok_zemli', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Соток земли')),
                ('etagnost', models.IntegerField(verbose_name='Этажность')),
                ('nazn_zemli', models.CharField(choices=[('ИЖС', 'ИЖС'), ('СНТ', 'СНТ'), ('ЛПХ', 'ЛПХ')], max_length=10, verbose_name='Назначение земли')),
                ('documenti', models.CharField(choices=[('Кадастр', 'Кадастр'), ('Тех.паспорт', 'Тех.паспорт'), ('Разр.на строительство', 'Разр.на строительство'), ('Свидетельство', 'Свидетельство')], max_length=45, verbose_name='Документы')),
                ('cena_sobstv', models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена собственника')),
                ('cena_agenstv', models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена агенства')),
                ('prim', models.TextField(verbose_name='Примечание')),
                ('closed', models.BooleanField(default=False, verbose_name='Обьект продан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name_plural': 'Дом',
                'verbose_name': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazv', models.CharField(default='', max_length=100, verbose_name='азвание:')),
                ('date_sozd', models.DateField(auto_now=True)),
                ('street', models.CharField(max_length=35, verbose_name='Улица:')),
                ('komnat', models.IntegerField(verbose_name='Кол-во комнат:')),
                ('prais', models.IntegerField(validators=[django.core.validators.MinValueValidator(850000)], verbose_name='Цена:')),
                ('etagnost', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('9', '9'), ('10', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('19', '19'), ('20', '21'), ('21', '21'), ('22', '22')], max_length=3, verbose_name='Этажность')),
                ('etag', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('9', '9'), ('10', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('19', '19'), ('20', '21'), ('21', '21'), ('22', '22')], max_length=3, verbose_name='Этаж:')),
                ('plosgad', models.IntegerField(default='10', validators=[django.core.validators.MinValueValidator(10)], verbose_name='Общая площадь:')),
                ('note', models.CharField(max_length=225, verbose_name='Описание')),
                ('pub', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Публикация:')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор:')),
            ],
            options={
                'verbose_name_plural': 'Выгрузки',
                'verbose_name': 'Выгрузка',
            },
        ),
        migrations.CreateModel(
            name='feed_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('pict', models.ImageField(upload_to='upload_path/%s/%s/%s.jpg', verbose_name='Картинка')),
                ('id_gal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idd_gal', to='crm.feed')),
            ],
            options={
                'verbose_name_plural': 'Выгрузки галереея',
                'verbose_name': 'Выгрузки галерея',
            },
        ),
        migrations.CreateModel(
            name='flat_obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('client_tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='тел клиента')),
                ('datep', models.DateField(auto_now=True, verbose_name='Дата публикации')),
                ('status_obj', models.CharField(choices=[('Опубликован', 'Опубликован'), ('Не опубликован', 'Не опубликован')], default='Опубликован', max_length=45, verbose_name='Публикация обьекта')),
                ('raion', models.CharField(choices=[('Ахун', 'Ахун'), ('Адлер', 'Адлер'), ('Бытха', 'Бытха'), ('Виноградная', 'Виноградная'), ('Дагомыс', 'Дагомыс'), ('Донская', 'Донская'), ('Донская(Пасечная)', 'Донская(Пасечная)'), ('Донская(Тимерярева)', 'Донская(Тимерярева)'), ('Завокзальный', 'Завокзальный'), ('Заречный', 'Заречный'), ('Клубничная', 'Клубничная'), ('КСМ', 'КСМ'), ('Красная поляна', 'Красная поляна'), ('Кудепста', 'Кудепста'), ('Макаренко', 'Макаренко'), ('Мамайка', 'Мамайка'), ('Мамайский перевал', 'Мамайский перевал'), ('Мацеста', 'Мацеста'), ('Н.Сочи', 'Н.Сочи'), ('Объезная', 'Объезная'), ('Пластунская', 'Пластунская'), ('Приморье', 'Приморье'), ('Раздольное', 'Раздольное'), ('Светлана', 'Светлана'), ('Соболевка', 'Соболевка'), ('Транспортная', 'Транспортная'), ('Фабрициуса', 'Фабрициуса'), ('Хоста', 'Хоста'), ('Центр', 'Центр')], default='Адрес', max_length=20, verbose_name='Район')),
                ('adress', models.CharField(max_length=70, verbose_name='Адрес:')),
                ('etap_sdachi', models.CharField(choices=[('Не сдан', 'Не сдан'), ('Рег.УФРС', 'Рег.УФРС'), ('ФЗ-214', 'ФЗ-214'), ('ФЗ-215', 'ФЗ-215'), ('Сдан', 'Сдан')], max_length=40, verbose_name='Этап сдачи')),
                ('status_gilya', models.CharField(choices=[('Жилое помещение', 'Жилое помещение'), ('Нежилое помещение', 'Нежилое помещение'), ('Часть жил.дома', 'Часть жил.дома'), ('Квартира', 'Квартира'), ('Комната', 'Комната')], max_length=40, verbose_name='Статус жилья')),
                ('klass_gilya', models.CharField(choices=[('Эконом', 'Эконом'), ('Комфорт', 'Комфорт'), ('Бизнес', 'Бизнес'), ('Элит', 'Элит')], max_length=45, verbose_name='Класс жилья')),
                ('kredit', multiselectfield.db.fields.MultiSelectField(choices=[('Ипотека СберБанк', 'Ипотека СберБанк'), ('Ипотека РоссельхозБанк', 'Ипотека РоссельхозБанк'), ('Ипотека ВТБ24', 'Ипотека ВТБ24'), ('Мат.капитал', 'Мат капитал'), ('Воен ипотека', 'Воен ипотека'), ('Рассрочка', 'Рассрочка'), ('Только наличные', 'Только наличными')], max_length=104, verbose_name='Усл.Кредита')),
                ('remont', models.CharField(choices=[('Черновой', 'Черновой'), ('Чистовой', 'Чистовой'), ('Дизайнерский', 'Дизайнерский'), ('Жилой', 'Жилой'), ('Новый', 'Новый')], max_length=25, verbose_name='Ремонт')),
                ('gaz', models.CharField(choices=[('Нет', 'Нет'), ('Есть', 'Есть'), ('Можно подключить', 'Можно подключить'), ('В процессе подключения', 'В процессе подключения')], max_length=40, verbose_name='Газ')),
                ('komnat', models.CharField(choices=[('Студия', 'Студия'), ('Однокомнатная', 'Однокомнатная'), ('Двухкомнатная', 'Двухкомнатная'), ('Трехкомнатная', 'Трехкомнатная'), ('Многокомнатная', 'Многокомнатная')], max_length=25, verbose_name='Кол-во комнат')),
                ('ploshad', models.IntegerField(verbose_name='Площадь')),
                ('etag', models.IntegerField(verbose_name='Этаж')),
                ('vid_is_okon', models.CharField(choices=[('Обычный', 'Обычный'), ('На стену', 'На стену'), ('На море', 'На море'), ('На горы', 'На горы')], max_length=25, verbose_name='Вид из окон')),
                ('san_usel', models.CharField(choices=[('Совмещенный', 'Совмещенный'), ('Раздельный', 'Раздельный')], max_length=15, verbose_name='Санузел')),
                ('parking', models.CharField(choices=[('Есть', 'Есть'), ('Нет', 'Нет'), ('Подземный', 'Подземный')], max_length=15, verbose_name='Паркинг')),
                ('cena_sobstv', models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена собственника')),
                ('cena_agenstv', models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена агенства')),
                ('prim', models.TextField(verbose_name='Примечание')),
                ('closed', models.BooleanField(default=False, verbose_name='Клиент закрыт')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name_plural': 'Квартиры',
                'verbose_name': 'Квартира',
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazv', models.CharField(max_length=10, verbose_name='Название')),
                ('text', models.TextField(max_length=450, verbose_name='Текст')),
                ('datep', models.DateField(blank=True, verbose_name='Дата публикации')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='otchet_nov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sozd', models.DateField(auto_now=True, verbose_name='Дата сделки:')),
                ('nazv_nov', models.CharField(max_length=140, verbose_name='Название новостройки:')),
                ('fio_kl', models.CharField(max_length=50, verbose_name='ФИО клиента:')),
                ('tel_kl', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='тел.Клиента:')),
                ('rielt_proc', models.IntegerField(default=100, verbose_name='Проценты:')),
                ('ploshad', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Площадь:')),
                ('stoimost', models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена:')),
                ('komisia', models.IntegerField(validators=[django.core.validators.MinValueValidator(30000)], verbose_name='Комисия:')),
                ('ipoteka', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3, verbose_name='Ипотека:')),
                ('rasrochka', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3, verbose_name='Расрочка:')),
                ('rielt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Риелтор:')),
            ],
            options={
                'verbose_name_plural': 'Отчеты по сделке(Нов.)',
                'verbose_name': 'Отчет по сделке(Нов.)',
            },
        ),
        migrations.CreateModel(
            name='otchet_nov_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sd', models.DateField(verbose_name='Дата:')),
                ('nazv_nov_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.otchet_nov')),
            ],
            options={
                'verbose_name_plural': 'Спр. дат сделок',
                'verbose_name': 'Спр. даты сделок',
            },
        ),
        migrations.CreateModel(
            name='otchet_nov_reeltsp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc', models.IntegerField(verbose_name='Проценты')),
                ('reelt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Риелтор в сделке:')),
                ('sdelka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.otchet_nov')),
            ],
            options={
                'verbose_name_plural': 'Сп.риелтор в сделке',
                'verbose_name': 'Сп.риелтор в сделке',
            },
        ),
        migrations.CreateModel(
            name='uchastok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_fio', models.CharField(max_length=45, verbose_name='Клиент(ФИО)')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Телефон клиента(+79881234567)')),
                ('date_sozd', models.DateField(auto_now=True, verbose_name='Дата создания:')),
                ('status_obj', models.CharField(choices=[('Опубликован', 'Опубликован'), ('Не опубликован', 'Не опубликован')], max_length=45, verbose_name='Публикация обьекта')),
                ('raion', models.CharField(choices=[('Ахун', 'Ахун'), ('Адлер', 'Адлер'), ('Бытха', 'Бытха'), ('Виноградная', 'Виноградная'), ('Дагомыс', 'Дагомыс'), ('Донская', 'Донская'), ('Донская(Пасечная)', 'Донская(Пасечная)'), ('Донская(Тимерярева)', 'Донская(Тимерярева)'), ('Завокзальный', 'Завокзальный'), ('Заречный', 'Заречный'), ('Клубничная', 'Клубничная'), ('КСМ', 'КСМ'), ('Красная поляна', 'Красная поляна'), ('Кудепста', 'Кудепста'), ('Макаренко', 'Макаренко'), ('Мамайка', 'Мамайка'), ('Мамайский перевал', 'Мамайский перевал'), ('Мацеста', 'Мацеста'), ('Н.Сочи', 'Н.Сочи'), ('Объезная', 'Объезная'), ('Пластунская', 'Пластунская'), ('Приморье', 'Приморье'), ('Раздольное', 'Раздольное'), ('Светлана', 'Светлана'), ('Соболевка', 'Соболевка'), ('Транспортная', 'Транспортная'), ('Фабрициуса', 'Фабрициуса'), ('Хоста', 'Хоста'), ('Центр', 'Центр')], max_length=45, verbose_name='Район:')),
                ('adress', models.CharField(max_length=70, verbose_name='Адрес:')),
                ('comunications', models.CharField(choices=[('На участке', 'На участке'), ('На границе', 'На границе'), ('Нет', 'Нет')], max_length=25, verbose_name='Комуникации')),
                ('gaz', models.CharField(choices=[('Нет', 'Нет'), ('Есть', 'Есть'), ('Можно подключить', 'Можно подключить'), ('В процессе подключения', 'В процессе подключения')], max_length=45, verbose_name='Газ')),
                ('nazn_zemli', models.CharField(choices=[('ИЖС', 'ИЖС'), ('СНТ', 'СНТ'), ('ЛПХ', 'ЛПХ'), ('ЖЧ', 'ЖЧ')], max_length=10, verbose_name='Назначение земли')),
                ('documenti', models.CharField(choices=[('Кадастр', 'Кадастр'), ('Тех.паспорт', 'Тех.паспорт'), ('Разр.на строительство', 'Разр.на строительство'), ('Свидетельство', 'Свидетельство')], max_length=45, verbose_name='Документы')),
                ('ploshad', models.IntegerField(verbose_name='Площадь(соток)')),
                ('cena_sobstv', models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена собственника')),
                ('cena_agenstv', models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена агенства')),
                ('prim', models.TextField(verbose_name='Примечание')),
                ('closed', models.BooleanField(default=False, verbose_name='Обьект продан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name_plural': 'Участки',
                'verbose_name': 'Участки',
            },
        ),
        migrations.CreateModel(
            name='UserProfile1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
                'verbose_name': 'Профиль',
            },
        ),
    ]
