# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='cel_pokupki',
        ),
    ]
