# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20171002_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date_sozd',
            field=models.DateField(auto_now=True, verbose_name='Дата создания:'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='plosgad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Общая площадь:'),
        ),
    ]
