# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 12:55
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_clients_cel_pokupki'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='cel_pokupki',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ПМЖ', 'ПМЖ'), ('Аренда/Для сдачи', 'Аренда/Для сдачи'), ('Инвестирование', 'Инвестирование')], default=1, max_length=35, verbose_name='Цель покупки'),
            preserve_default=False,
        ),
    ]
