# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 13:16
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_clients_cel_pokupki'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='st_pub',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Только у себя', 'Только у себя'), ('Видно в отделе', 'Только у себя'), ('Видно всем', 'Только у себя')], default='Только у себя', max_length=39, verbose_name='Oпубликовать в:'),
        ),
    ]
