# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_clients_st_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clients',
            name='st_pub',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Только у себя', 'Только у себя'), ('Видно в отделе', 'Видно в отделе'), ('Видно всем', 'Видно всем')], default='Только у себя', max_length=39, verbose_name='Oпубликовать в:'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Телефон клиента(+79881234567)'),
        ),
    ]
