# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20171004_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed_gallery',
            name='pict',
        ),
        migrations.AddField(
            model_name='feed_gallery',
            name='npict',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото объекта'),
        ),
    ]
