# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20171004_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed_gallery',
            options={'verbose_name': 'Выгрузки галерея', 'verbose_name_plural': 'Выгрузки галерея'},
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_sozd',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='feed_gallery',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='feed_gallery',
            name='id_gal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idd_gal', to='crm.feed', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='feed_gallery',
            name='npict',
            field=models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото объекта'),
        ),
    ]
