# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20170728_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='otd',
            field=models.CharField(default=' ', max_length=45, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Клиент закрыт'),
        ),
    ]
