# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 13:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20170801_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_obj',
            name='cena_agenstv',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена агенства'),
        ),
        migrations.AlterField(
            model_name='flat_obj',
            name='cena_sobstv',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена собственника'),
        ),
        migrations.AlterField(
            model_name='flat_obj',
            name='kredit',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ипотека СберБанк', 'Ипотека СберБанк'), ('Ипотека РоссельхозБанк', 'Ипотека РоссельхозБанк'), ('Ипотека ВТБ24', 'Ипотека ВТБ24'), ('Мат.капитал', 'Мат капитал'), ('Воен ипотека', 'Воен ипотека'), ('Рассрочка', 'Рассрочка')], max_length=88, verbose_name='Усл.Кредита'),
        ),
    ]
