# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 10:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20170801_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='doma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_fio', models.CharField(max_length=45, verbose_name='Клиент(ФИО)')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Телефон клиента(+79881234567)')),
                ('date_sozd', models.DateField(auto_now=True, verbose_name='Дата создания:')),
                ('status_obj', models.CharField(choices=[('Опубликован', 'Опубликован'), ('Не опубликован', 'Не опубликован')], default='Опубликован', max_length=45, verbose_name='Публикация обьекта')),
                ('raion', models.CharField(choices=[('Ахун', 'Ахун'), ('Бытха', 'Бытха'), ('Дагомыс', 'Дагомыс'), ('Донская', 'Донская'), ('Донская', 'Донская'), ('Завокзальный', 'Завокзальный'), ('Заречный', 'Заречный'), ('Клубничная', 'Клубничная'), ('Красная поляна', 'Красная поляна'), ('Кудепста', 'Кудепста'), ('Макаренко', 'Макаренко'), ('Мамайка', 'Мамайка'), ('Мамайский перевал', 'Мамайский перевал'), ('Мацеста', 'Мацеста'), ('Н.Сочи', 'Н.Сочи'), ('Объезная', 'Объезная'), ('Приморье', 'Приморье'), ('Раздольное', 'Раздольное'), ('Светлана', 'Светлана'), ('Транспортная', 'Транспортная'), ('Фабрициуса', 'Фабрициуса'), ('Хоста', 'Хоста'), ('Центр', 'Центр')], max_length=45, verbose_name='Район:')),
                ('type_house', models.CharField(choices=[('Каркастный', 'Каркастный'), ('Монолит', 'Монолит'), ('Кирпич', 'Кирпич')], max_length=55, verbose_name='Тип дома')),
                ('ploshad_doma', models.DecimalField(decimal_places=2, default=11.11, max_digits=4, verbose_name='Площадь дома')),
                ('remont', models.CharField(choices=[('Черновой', 'Черновой'), ('Чистовой', 'Чистовой'), ('Дизайнерский', 'Дизайнерский')], max_length=55, verbose_name='Ремонт')),
                ('canalizacia', models.CharField(choices=[('ЛОС', 'ЛОС'), ('Септик', 'Септик'), ('Септик', 'Септик')], max_length=45, verbose_name='Канализация')),
                ('gaz', models.CharField(choices=[('Нет', 'Нет'), ('Есть', 'Есть'), ('Можно подключить', 'Можно подключить'), ('В процессе подключения', 'В процессе подключения')], max_length=45, verbose_name='')),
                ('svet', models.IntegerField(verbose_name='Свет(квт)')),
                ('voda', models.CharField(choices=[('Скважена', 'Скважена'), ('Центролизованное', 'Центролизованное'), ('Можно подключить', 'Можно подключить')], max_length=45, verbose_name='Водоснабжение')),
                ('komnat', models.IntegerField(verbose_name='Кол-во комнат')),
                ('sotok_zemli', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Соток земли')),
                ('etagnost', models.IntegerField(verbose_name='Этажность')),
                ('nazn_zemli', models.CharField(choices=[('ИЖС', 'ИЖС'), ('СНТ', 'СНТ'), ('ЛПХ', 'ЛПХ')], max_length=10, verbose_name='Назначение земли')),
                ('documenti', models.CharField(choices=[('Кадастр', 'Кадастр'), ('Тех.паспорт', 'Тех.паспорт'), ('Разр.на строительство', 'Разр.на строительство')], max_length=45, verbose_name='Документы')),
                ('cena_sobstv', models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена собственника')),
                ('cena_agenstv', models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена агенства')),
                ('prim', models.TextField(verbose_name='Примечание')),
                ('closed', models.BooleanField(default=False, verbose_name='Обьект продан')),
            ],
            options={
                'verbose_name_plural': 'Дом',
                'verbose_name': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='uchastok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_fio', models.CharField(max_length=45, verbose_name='Клиент(ФИО)')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Телефон клиента(+79881234567)')),
                ('date_sozd', models.DateField(auto_now=True, verbose_name='Дата создания:')),
                ('status_obj', models.CharField(choices=[('Опубликован', 'Опубликован'), ('Не опубликован', 'Не опубликован')], default='Опубликован', max_length=45, verbose_name='Публикация обьекта')),
                ('raion', models.CharField(choices=[('Ахун', 'Ахун'), ('Бытха', 'Бытха'), ('Дагомыс', 'Дагомыс'), ('Донская', 'Донская'), ('Донская', 'Донская'), ('Завокзальный', 'Завокзальный'), ('Заречный', 'Заречный'), ('Клубничная', 'Клубничная'), ('Красная поляна', 'Красная поляна'), ('Кудепста', 'Кудепста'), ('Макаренко', 'Макаренко'), ('Мамайка', 'Мамайка'), ('Мамайский перевал', 'Мамайский перевал'), ('Мацеста', 'Мацеста'), ('Н.Сочи', 'Н.Сочи'), ('Объезная', 'Объезная'), ('Приморье', 'Приморье'), ('Раздольное', 'Раздольное'), ('Светлана', 'Светлана'), ('Транспортная', 'Транспортная'), ('Фабрициуса', 'Фабрициуса'), ('Хоста', 'Хоста'), ('Центр', 'Центр')], max_length=45, verbose_name='Район:')),
                ('comunications', models.CharField(max_length=25, verbose_name='Комуникации')),
                ('gaz', models.CharField(choices=[('Нет', 'Нет'), ('Есть', 'Есть'), ('Можно подключить', 'Можно подключить'), ('В процессе подключения', 'В процессе подключения')], max_length=45, verbose_name='')),
                ('nazn_zemli', models.CharField(choices=[('ИЖС', 'ИЖС'), ('СНТ', 'СНТ'), ('ЛПХ', 'ЛПХ'), ('ЖЧ', 'ЖЧ')], max_length=10, verbose_name='Назначение земли')),
                ('documenti', models.CharField(choices=[('Кадастр', 'Кадастр'), ('Тех.паспорт', 'Тех.паспорт'), ('Разр.на строительство', 'Разр.на строительство')], max_length=45, verbose_name='Документы')),
                ('cena_sobstv', models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена собственника')),
                ('cena_agenstv', models.IntegerField(validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена агенства')),
                ('prim', models.TextField(verbose_name='Примечание')),
                ('closed', models.BooleanField(default=False, verbose_name='Обьект продан')),
            ],
            options={
                'verbose_name_plural': 'Участок',
                'verbose_name': 'Участки',
            },
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Клиент закрыт'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(default='nomail@nomail.ru', max_length=254, verbose_name='email клиента'),
        ),
    ]
