# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20171005_1254'),
        ('crm', '0012_auto_20170914_1450'),
    ]

    operations = [
    ]
