# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20171006_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile1',
            name='tel',
            field=models.IntegerField(help_text='9881112233', max_length=10, verbose_name='Телефон'),
        ),
    ]
