# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20171116_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat_obj',
            name='domclick',
        ),
        migrations.RemoveField(
            model_name='flat_obj',
            name='domclick_pub',
        ),
    ]
