# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 12:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20171130_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='raion',
            field=models.CharField(blank=True, choices=[('Адлерский', 'Адлерский'), ('Бытха', 'Бытха'), ('Дагомыс', 'Дагомыс'), ('Донская', 'Донская'), ('Завокзальный', 'Завокзальный'), ('Заречный', 'Заречный'), ('Краснодарское кольцо', 'Краснодарское кольцо'), ('КСМ', 'КСМ'), ('Макаренко', 'Макренко'), ('Мамайка', 'Мамайка'), ('Мацеста', 'Мацеста'), ('Н. Сочи', 'Н.Сочи'), ('Приморье', 'Приморье'), ('Светлана', 'Светлана'), ('Соболевка', 'Соболевка'), ('Стадион', 'Стадион'), ('Хостинский', 'Хостинский'), ('Центр', 'Центр')], max_length=15, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='feed',
            name='vb_pub',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3, verbose_name='Публикация на вабанке'),
        ),
        migrations.AddField(
            model_name='userprofile1',
            name='vabanc',
            field=models.IntegerField(default=0, verbose_name='Балы Вабанк(Сочи-Экспресс)'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='raion',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ахун', 'Ахун'), ('Адлер', 'Адлер'), ('Бытха', 'Бытха'), ('Виноградная', 'Виноградная'), ('Дагомыс', 'Дагомыс'), ('Донская', 'Донская'), ('Донская(Пасечная)', 'Донская(Пасечная)'), ('Донская(Тимерязева)', 'Донская(Тимерязева)'), ('Завокзальный', 'Завокзальный'), ('Заречный', 'Заречный'), ('Клубничная', 'Клубничная'), ('КСМ', 'КСМ'), ('Красная поляна', 'Красная поляна'), ('Кудепста', 'Кудепста'), ('Макаренко', 'Макаренко'), ('Мамайка', 'Мамайка'), ('Мамайский перевал', 'Мамайский перевал'), ('Мацеста', 'Мацеста'), ('Н.Сочи', 'Н.Сочи'), ('Объезная', 'Объезная'), ('Пластунская', 'Пластунская'), ('Приморье', 'Приморье'), ('Раздольное', 'Раздольное'), ('Светлана', 'Светлана'), ('Соболевка', 'Соболевка'), ('Транспортная', 'Транспортная'), ('Фабрициуса', 'Фабрициуса'), ('Хоста', 'Хоста'), ('Центр', 'Центр'), ('(А) Блиново(+Вес)', '(А) Блиново(+Вес)'), ('(А) Гол. дали', '(А) Гол. дали'), ('(А) Кур.гор(+Чкал)', '(А) Кур.гор(+Чкал)'), ('(А) Мирный', '(А) Мирный'), ('(А) Молдовка', '(А) Молдовка'), ('(А) Центр', '(А) Центр'), ('(А) Чай совхоз', '(А) Чай совхоз')], max_length=390, verbose_name='Район:'),
        ),
        migrations.AlterField(
            model_name='doma',
            name='client_fio',
            field=models.CharField(max_length=45, verbose_name='Cобственник(ФИО)'),
        ),
        migrations.AlterField(
            model_name='doma',
            name='raion',
            field=models.CharField(choices=[('Ахун', 'Ахун'), ('Адлер', 'Адлер'), ('Бытха', 'Бытха'), ('Виноградная', 'Виноградная'), ('Дагомыс', 'Дагомыс'), ('Донская', 'Донская'), ('Донская(Пасечная)', 'Донская(Пасечная)'), ('Донская(Тимерязева)', 'Донская(Тимерязева)'), ('Завокзальный', 'Завокзальный'), ('Заречный', 'Заречный'), ('Клубничная', 'Клубничная'), ('КСМ', 'КСМ'), ('Красная поляна', 'Красная поляна'), ('Кудепста', 'Кудепста'), ('Макаренко', 'Макаренко'), ('Мамайка', 'Мамайка'), ('Мамайский перевал', 'Мамайский перевал'), ('Мацеста', 'Мацеста'), ('Н.Сочи', 'Н.Сочи'), ('Объезная', 'Объезная'), ('Пластунская', 'Пластунская'), ('Приморье', 'Приморье'), ('Раздольное', 'Раздольное'), ('Светлана', 'Светлана'), ('Соболевка', 'Соболевка'), ('Транспортная', 'Транспортная'), ('Фабрициуса', 'Фабрициуса'), ('Хоста', 'Хоста'), ('Центр', 'Центр'), ('(А) Блиново(+Вес)', '(А) Блиново(+Вес)'), ('(А) Гол. дали', '(А) Гол. дали'), ('(А) Кур.гор(+Чкал)', '(А) Кур.гор(+Чкал)'), ('(А) Мирный', '(А) Мирный'), ('(А) Молдовка', '(А) Молдовка'), ('(А) Центр', '(А) Центр'), ('(А) Чай совхоз', '(А) Чай совхоз')], max_length=45, verbose_name='Район:'),
        ),
        migrations.AlterField(
            model_name='doma',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Телефон собственника(+79881234567)'),
        ),
        migrations.AlterField(
            model_name='flat_obj',
            name='client_name',
            field=models.CharField(max_length=50, verbose_name='Имя собственника'),
        ),
        migrations.AlterField(
            model_name='flat_obj',
            name='client_tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='тел собственника'),
        ),
        migrations.AlterField(
            model_name='flat_obj',
            name='closed',
            field=models.BooleanField(default=False, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Клиент закрыт'),
        ),
        migrations.AlterField(
            model_name='flat_obj',
            name='kadastr',
            field=models.CharField(blank=True, help_text='Необязательно к заполнению', max_length=18, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Кадастровый номер'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='client_fio',
            field=models.CharField(max_length=45, verbose_name='Cобственник(ФИО)'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='raion',
            field=models.CharField(choices=[('Ахун', 'Ахун'), ('Адлер', 'Адлер'), ('Бытха', 'Бытха'), ('Виноградная', 'Виноградная'), ('Дагомыс', 'Дагомыс'), ('Донская', 'Донская'), ('Донская(Пасечная)', 'Донская(Пасечная)'), ('Донская(Тимерязева)', 'Донская(Тимерязева)'), ('Завокзальный', 'Завокзальный'), ('Заречный', 'Заречный'), ('Клубничная', 'Клубничная'), ('КСМ', 'КСМ'), ('Красная поляна', 'Красная поляна'), ('Кудепста', 'Кудепста'), ('Макаренко', 'Макаренко'), ('Мамайка', 'Мамайка'), ('Мамайский перевал', 'Мамайский перевал'), ('Мацеста', 'Мацеста'), ('Н.Сочи', 'Н.Сочи'), ('Объезная', 'Объезная'), ('Пластунская', 'Пластунская'), ('Приморье', 'Приморье'), ('Раздольное', 'Раздольное'), ('Светлана', 'Светлана'), ('Соболевка', 'Соболевка'), ('Транспортная', 'Транспортная'), ('Фабрициуса', 'Фабрициуса'), ('Хоста', 'Хоста'), ('Центр', 'Центр'), ('(А) Блиново(+Вес)', '(А) Блиново(+Вес)'), ('(А) Гол. дали', '(А) Гол. дали'), ('(А) Кур.гор(+Чкал)', '(А) Кур.гор(+Чкал)'), ('(А) Мирный', '(А) Мирный'), ('(А) Молдовка', '(А) Молдовка'), ('(А) Центр', '(А) Центр'), ('(А) Чай совхоз', '(А) Чай совхоз')], max_length=45, verbose_name='Район:'),
        ),
        migrations.AlterField(
            model_name='uchastok',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Телефон собственника(+79881234567)'),
        ),
        migrations.AlterField(
            model_name='userprofile1',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idd_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
