# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 13:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20171208_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otchet_nov_date',
            name='nazv_nov_id',
        ),
        migrations.RemoveField(
            model_name='otchet_nov_reeltsp',
            name='reelt',
        ),
        migrations.RemoveField(
            model_name='otchet_nov_reeltsp',
            name='sdelka_id',
        ),
        migrations.AlterModelOptions(
            name='otchet_nov',
            options={'verbose_name': 'Отчет по сделке', 'verbose_name_plural': 'Отчеты по сделке'},
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='date_zakr',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата закрытия сделки:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='prim',
            field=models.CharField(blank=True, default=' ', max_length=1050, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='reelt1',
            field=models.CharField(blank=True, choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Дмитрий Черенков'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('isurina', 'Ирина Сурина'), ('kvoskanyan', 'Кирилл Восканян'), ('agukova', 'Анна Жукова'), ('voskakyand', 'Давид Восканян'), ('shestakovam', 'Манана Шестакова'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('zalubovskiya', 'Алексей Залюбовский'), ('shalaeva', 'Наталья Барыбина'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('molchanovar', 'Римма Молчанова'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №1'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='reelt10',
            field=models.CharField(blank=True, choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Дмитрий Черенков'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('isurina', 'Ирина Сурина'), ('kvoskanyan', 'Кирилл Восканян'), ('agukova', 'Анна Жукова'), ('voskakyand', 'Давид Восканян'), ('shestakovam', 'Манана Шестакова'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('zalubovskiya', 'Алексей Залюбовский'), ('shalaeva', 'Наталья Барыбина'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('molchanovar', 'Римма Молчанова'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №10'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='reelt2',
            field=models.CharField(blank=True, choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Дмитрий Черенков'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('isurina', 'Ирина Сурина'), ('kvoskanyan', 'Кирилл Восканян'), ('agukova', 'Анна Жукова'), ('voskakyand', 'Давид Восканян'), ('shestakovam', 'Манана Шестакова'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('zalubovskiya', 'Алексей Залюбовский'), ('shalaeva', 'Наталья Барыбина'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('molchanovar', 'Римма Молчанова'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №2'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='reelt3',
            field=models.CharField(blank=True, choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Дмитрий Черенков'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('isurina', 'Ирина Сурина'), ('kvoskanyan', 'Кирилл Восканян'), ('agukova', 'Анна Жукова'), ('voskakyand', 'Давид Восканян'), ('shestakovam', 'Манана Шестакова'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('zalubovskiya', 'Алексей Залюбовский'), ('shalaeva', 'Наталья Барыбина'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('molchanovar', 'Римма Молчанова'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №3'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='reelt4',
            field=models.CharField(blank=True, choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Дмитрий Черенков'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('isurina', 'Ирина Сурина'), ('kvoskanyan', 'Кирилл Восканян'), ('agukova', 'Анна Жукова'), ('voskakyand', 'Давид Восканян'), ('shestakovam', 'Манана Шестакова'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('zalubovskiya', 'Алексей Залюбовский'), ('shalaeva', 'Наталья Барыбина'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('molchanovar', 'Римма Молчанова'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №4'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='reelt5',
            field=models.CharField(blank=True, choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Дмитрий Черенков'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('isurina', 'Ирина Сурина'), ('kvoskanyan', 'Кирилл Восканян'), ('agukova', 'Анна Жукова'), ('voskakyand', 'Давид Восканян'), ('shestakovam', 'Манана Шестакова'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('zalubovskiya', 'Алексей Залюбовский'), ('shalaeva', 'Наталья Барыбина'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('molchanovar', 'Римма Молчанова'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №5'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='reelt6',
            field=models.CharField(blank=True, choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Дмитрий Черенков'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('isurina', 'Ирина Сурина'), ('kvoskanyan', 'Кирилл Восканян'), ('agukova', 'Анна Жукова'), ('voskakyand', 'Давид Восканян'), ('shestakovam', 'Манана Шестакова'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('zalubovskiya', 'Алексей Залюбовский'), ('shalaeva', 'Наталья Барыбина'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('molchanovar', 'Римма Молчанова'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №6'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='reelt7',
            field=models.CharField(blank=True, choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Дмитрий Черенков'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('isurina', 'Ирина Сурина'), ('kvoskanyan', 'Кирилл Восканян'), ('agukova', 'Анна Жукова'), ('voskakyand', 'Давид Восканян'), ('shestakovam', 'Манана Шестакова'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('zalubovskiya', 'Алексей Залюбовский'), ('shalaeva', 'Наталья Барыбина'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('molchanovar', 'Римма Молчанова'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №7'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='reelt8',
            field=models.CharField(blank=True, choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Дмитрий Черенков'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('isurina', 'Ирина Сурина'), ('kvoskanyan', 'Кирилл Восканян'), ('agukova', 'Анна Жукова'), ('voskakyand', 'Давид Восканян'), ('shestakovam', 'Манана Шестакова'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('zalubovskiya', 'Алексей Залюбовский'), ('shalaeva', 'Наталья Барыбина'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('molchanovar', 'Римма Молчанова'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №8'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='reelt9',
            field=models.CharField(blank=True, choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Дмитрий Черенков'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('isurina', 'Ирина Сурина'), ('kvoskanyan', 'Кирилл Восканян'), ('agukova', 'Анна Жукова'), ('voskakyand', 'Давид Восканян'), ('shestakovam', 'Манана Шестакова'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('zalubovskiya', 'Алексей Залюбовский'), ('shalaeva', 'Наталья Барыбина'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('molchanovar', 'Римма Молчанова'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №9'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='rielt_proc1',
            field=models.IntegerField(blank=True, default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №1 в сделке:'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='rielt_proc10',
            field=models.IntegerField(blank=True, default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №10 в сделке:'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='rielt_proc2',
            field=models.IntegerField(blank=True, default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №2 в сделке:'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='rielt_proc3',
            field=models.IntegerField(blank=True, default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №3 в сделке:'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='rielt_proc4',
            field=models.IntegerField(blank=True, default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №4 в сделке:'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='rielt_proc5',
            field=models.IntegerField(blank=True, default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №5 в сделке:'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='rielt_proc6',
            field=models.IntegerField(blank=True, default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №6 в сделке:'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='rielt_proc7',
            field=models.IntegerField(blank=True, default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №7 в сделке:'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='rielt_proc8',
            field=models.IntegerField(blank=True, default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №8 в сделке:'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='rielt_proc9',
            field=models.IntegerField(blank=True, default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №9 в сделке:'),
        ),
        migrations.AddField(
            model_name='otchet_nov',
            name='status_sdelki',
            field=models.CharField(choices=[('Открыта', 'Открыта'), ('Закрыта', 'Закрыта')], default='Открыта', max_length=15, verbose_name='Статус сделки'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='komisia',
            field=models.IntegerField(help_text='min 30 000', validators=[django.core.validators.MinValueValidator(30000)], verbose_name='Комисия:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='nazv_nov',
            field=models.CharField(max_length=140, verbose_name='Название объекта:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='ploshad',
            field=models.DecimalField(decimal_places=2, help_text='min 5', max_digits=4, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Площадь:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='stoimost',
            field=models.IntegerField(help_text='min 300 000', validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Стоимость объекта:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='tel_kl',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='(+79881234567)', max_length=128, verbose_name='тел.Клиента:'),
        ),
        migrations.DeleteModel(
            name='otchet_nov_date',
        ),
        migrations.DeleteModel(
            name='otchet_nov_reeltsp',
        ),
    ]
