# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20171019_1251'),
        ('crm', '0023_auto_20171214_1648'),
    ]

    operations = [
    ]
