# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_auto_20180108_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='otchet_nov',
            name='ot_kuda_kl',
            field=models.CharField(choices=[('Другое', 'Другое'), ('Avito', 'Avito'), ('Cian', 'Cian'), ('Сайт компании', 'Сайт компании'), ('По рекомендации', 'По рекомендации')], default='По рекомендации', max_length=15, verbose_name='Канал привлечения клиента:'),
        ),
    ]
