# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 12:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_otchet_nov_ot_kuda_kl'),
    ]

    operations = [
        migrations.AddField(
            model_name='otchet_nov',
            name='sdelka_zakrita',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Сделка закрыта'),
        ),
        migrations.AlterField(
            model_name='flat_obj',
            name='prim',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='date_sozd',
            field=models.DateField(verbose_name='Дата сделки:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='ot_kuda_kl',
            field=models.CharField(choices=[('Другое', 'Другое'), ('Avito', 'Avito'), ('Avito Turbo', 'Avito Turbo'), ('Cian', 'Cian'), ('Сайт компании', 'Сайт компании'), ('По рекомендации', 'По рекомендации'), ('Домклик(Сбер)', 'Домклик(Сбер)'), ('Yandex Недвижимость', 'Yandex Недвижимость')], max_length=20, verbose_name='Канал привлечения клиента:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='reelt1',
            field=models.CharField(choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Эдуард Одабащьян'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий'), ('gukovaa', 'Анна Жукова'), ('klimovaf', 'Валентина Климкова')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №1'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='reelt10',
            field=models.CharField(blank=True, choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Эдуард Одабащьян'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий'), ('gukovaa', 'Анна Жукова'), ('klimovaf', 'Валентина Климкова')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №10'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='reelt2',
            field=models.CharField(choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Эдуард Одабащьян'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий'), ('gukovaa', 'Анна Жукова'), ('klimovaf', 'Валентина Климкова')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №2'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='reelt3',
            field=models.CharField(choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Эдуард Одабащьян'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий'), ('gukovaa', 'Анна Жукова'), ('klimovaf', 'Валентина Климкова')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №3'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='reelt4',
            field=models.CharField(choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Эдуард Одабащьян'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий'), ('gukovaa', 'Анна Жукова'), ('klimovaf', 'Валентина Климкова')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №4'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='reelt5',
            field=models.CharField(choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Эдуард Одабащьян'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий'), ('gukovaa', 'Анна Жукова'), ('klimovaf', 'Валентина Климкова')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №5'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='reelt6',
            field=models.CharField(choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Эдуард Одабащьян'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий'), ('gukovaa', 'Анна Жукова'), ('klimovaf', 'Валентина Климкова')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №6'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='reelt7',
            field=models.CharField(choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Эдуард Одабащьян'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий'), ('gukovaa', 'Анна Жукова'), ('klimovaf', 'Валентина Климкова')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №7'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='reelt8',
            field=models.CharField(choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Эдуард Одабащьян'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий'), ('gukovaa', 'Анна Жукова'), ('klimovaf', 'Валентина Климкова')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №8'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='reelt9',
            field=models.CharField(choices=[('homka', 'Роман Домников'), ('demo', 'demo demon'), ('surgutskayao', 'Оксана Сургутская'), ('alekseevau', 'Юлия Алексеева'), ('crutihinao', 'Ольга Крутихина'), ('mihailovau', 'Юлия Михайлова'), ('samoryadova', 'Андрей Саморядов'), ('shalimovav', 'Виктория Шалимова'), ('skripkinaa', 'Анастасия Скрипкина'), ('cherencovv', 'Эдуард Одабащьян'), ('rnovikov', 'Роман Новиков'), ('ujashakueva', 'Римма Джашакуева'), ('refremov', 'Руслан Ефремов'), ('aegorova', 'Анжелика Егорова'), ('livina', 'Людмила Ильина'), ('mkaskov', 'Максим Касков'), ('vorinchin', 'Владимир Оринчин'), ('novsyanikova', 'Нина Овсянникова'), ('rpoluvyanov', 'Роман Полувьянов'), ('isolovova', 'Инна Соловьева'), ('nsolovova', 'Наталья Соловьева'), ('paninv', 'Владислав Панин'), ('leontevd', 'Дмитрий Леонтьев'), ('makarovam', 'Марина Макарова'), ('maslovam', 'Марина Маслова'), ('novikove', 'Евгений Новиков'), ('stasukv', 'Вячеслав Стасюк'), ('zabolotiya', 'Алексей Заболотный'), ('liminae', 'Елена Лимина'), ('panasyka', 'Александр Панасюк'), ('tyrins', 'Сергей Тюрин'), ('zabolotiyd', 'Дмитрий Заболотный'), ('ivashenko', 'Алексей Иващенко'), ('jarkovan', 'Наталья Жаркова'), ('kazancevaa', 'Анастасия Казанцева'), ('mihailova', 'Антон Михайлов'), ('panochkin', 'Виктор Паночкин'), ('samodelovao', 'Ольга Самоделова'), ('samodelova', 'Андрей Самоделов'), ('shatskayan', 'Наталья Шацкая'), ('shutenkoa', 'Антон Шутенко'), ('sukhobaevskayam', 'Марина Сухобаевская'), ('timofeevas', 'Светлана Тимофеева'), ('uldasheva', 'Андрей Юлдашев'), ('tretuake', 'Евгений Третяк'), ('stepanovao', 'Ольга Степанова'), ('gukovau', 'Юлия Жукова'), ('maskarao', 'Оксана Машкара'), ('ermolovat', 'Татьяна Ермолова'), ('chelyadinovao', 'Ольга Челядинова'), ('savickayai', 'Ирина Савицкая'), ('milovanovv', 'Виктор Милованов'), ('golovind', 'Дмитрий Головин'), ('rudnevae', 'Елена Руднева'), ('cipurdeyo', 'Олег Ципурдей'), ('yaglova', 'Алексей Яглов'), ('deminaa', 'Анжелика Демина'), ('vishnevskiya', 'Александр Вишневецкий'), ('gukovaa', 'Анна Жукова'), ('klimovaf', 'Валентина Климкова')], default=' ', help_text='Необязательно к заполнению', max_length=100, verbose_name='Риелтор в сделке №9'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора-инициатора сделки:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc1',
            field=models.IntegerField(blank=True, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №1 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc10',
            field=models.IntegerField(blank=True, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №10 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc2',
            field=models.IntegerField(blank=True, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №2 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc3',
            field=models.IntegerField(blank=True, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №3 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc4',
            field=models.IntegerField(blank=True, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №4 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc5',
            field=models.IntegerField(blank=True, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №5 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc6',
            field=models.IntegerField(blank=True, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №6 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc7',
            field=models.IntegerField(blank=True, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №7 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc8',
            field=models.IntegerField(blank=True, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №8 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc9',
            field=models.IntegerField(blank=True, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №9 в сделке:'),
        ),
    ]
