# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 13:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_auto_20180129_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='otchet_nov',
            name='sdelka_zakrita',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Сделка закрыта'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='date_sozd',
            field=models.DateField(verbose_name='Дата сделки:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='ot_kuda_kl',
            field=models.CharField(choices=[('Другое', 'Другое'), ('Avito', 'Avito'), ('Avito Turbo', 'Avito Turbo'), ('Cian', 'Cian'), ('Сайт компании', 'Сайт компании'), ('По рекомендации', 'По рекомендации'), ('Домклик(Сбер)', 'Домклик(Сбер)'), ('Yandex Недвижимость', 'Yandex Недвижимость')], max_length=20, verbose_name='Канал привлечения клиента:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc1',
            field=models.IntegerField(default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №1 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc2',
            field=models.IntegerField(default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №2 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc3',
            field=models.IntegerField(default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №3 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc4',
            field=models.IntegerField(default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №4 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc5',
            field=models.IntegerField(default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №5 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc6',
            field=models.IntegerField(default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №6 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc7',
            field=models.IntegerField(default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №7 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc8',
            field=models.IntegerField(default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №8 в сделке:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc9',
            field=models.IntegerField(default=0, help_text='Необязательно к заполнению', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора №9 в сделке:'),
        ),
    ]
