# Generated by Django 2.0.1 on 2018-02-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_auto_20180129_1502'),
        ('crm', '0032_auto_20180129_1616'),
    ]

    operations = [
    ]
