# Generated by Django 2.0.1 on 2018-02-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_remove_flat_obj_kvart_numb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otchet_nov',
            name='rielt_proc',
        ),
        migrations.AlterField(
            model_name='flat_obj',
            name='dom_numb',
            field=models.CharField(default='', help_text='например: 11/2 или 16к (Буква обязательно маленкая!)', max_length=7, verbose_name='Номер дома:'),
        ),
    ]
