# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_auto_20180208_1330'),
        ('crm', '0035_auto_20180208_1231'),
    ]

    operations = [
    ]
