# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 11:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_merge_20180208_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='otchet_nov',
            name='rielt_proc',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проценты риелтора-инициатора сделки:'),
        ),
    ]
