# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0041_auto_20180208_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='zayavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=45, verbose_name='ФИО клиента:')),
                ('tel_kl', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='+79881234567', max_length=128, verbose_name='Тел клиента:')),
                ('raion', multiselectfield.db.fields.MultiSelectField(choices=[('Ахун', 'Ахун'), ('Адлер', 'Адлер'), ('Бытха', 'Бытха'), ('Виноградная', 'Виноградная'), ('Дагомыс', 'Дагомыс'), ('Донская', 'Донская'), ('Донская(Пасечная)', 'Донская(Пасечная)'), ('Донская(Тимерярева)', 'Донская(Тимерярева)'), ('Завокзальный', 'Завокзальный'), ('Заречный', 'Заречный'), ('Клубничная', 'Клубничная'), ('КСМ', 'КСМ'), ('Красная поляна', 'Красная поляна'), ('Кудепста', 'Кудепста'), ('Макаренко', 'Макаренко'), ('Мамайка', 'Мамайка'), ('Мамайский перевал', 'Мамайский перевал'), ('Мацеста', 'Мацеста'), ('Н.Сочи', 'Н.Сочи'), ('Объезная', 'Объезная'), ('Пластунская', 'Пластунская'), ('Приморье', 'Приморье'), ('Раздольное', 'Раздольное'), ('Светлана', 'Светлана'), ('Соболевка', 'Соболевка'), ('Транспортная', 'Транспортная'), ('Фабрициуса', 'Фабрициуса'), ('Хоста', 'Хоста'), ('Центр', 'Центр'), ('(А) Блиново(+Вес)', '(А) Блиново(+Вес)'), ('(А) Гол. дали', '(А) Гол. дали'), ('(А) Кур.гор(+Чкал)', '(А) Кур.гор(+Чкал)'), ('(А) Мирный', '(А) Мирный'), ('(А) Молдовка', '(А) Молдовка'), ('(А) Центр', '(А) Центр'), ('(А) Чай совхоз', '(А) Чай совхоз'), ('Неважно', 'Неважно')], default='Неважно', max_length=398, verbose_name='Район:')),
                ('komnat', models.CharField(choices=[('Студия', 'Студия'), ('Однокомнатная', 'Однокомнатная'), ('Двухкомнатная', 'Двухкомнатная'), ('Трехкомнатная', 'Трехкомнатная'), ('Многокомнатная', 'Многокомнатная'), ('Неважно', 'Неважно')], default='Неважно', max_length=25, verbose_name='Кол-во комнат:')),
                ('ploshad', models.IntegerField(default=0, verbose_name='Желаемая площадь:')),
                ('status', models.CharField(choices=[('Свободен', 'Свободен'), ('Взят в работу', 'Взят в работу'), ('Отказ клиента', 'Отказ клиента'), ('Уже купил', 'Уже купил'), ('Не дозвонились', 'Не дозвонились'), ('Сделка', 'Сделка'), ('Завышенные требования клиента', 'Завышенные требования клиента')], default='Свободен', max_length=45, verbose_name='Статус заявки')),
                ('author', models.CharField(max_length=25, verbose_name='Автор:')),
                ('date_sozd', models.DateField(auto_now=True, verbose_name='Дата создания:')),
                ('date_zakr', models.DateField(verbose_name='Дата закрытия:')),
                ('prim', models.CharField(blank=True, max_length=150, verbose_name='Примечание:')),
                ('kred_manager', models.CharField(default='', help_text='ФИО/тел.', max_length=150, verbose_name='Кредитный менеджер:')),
                ('reelt_v_rabote', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='В работе у:')),
            ],
            options={
                'verbose_name_plural': 'Заявки',
                'verbose_name': 'Заявки',
            },
        ),
        migrations.AlterField(
            model_name='feed_gallery',
            name='npict',
            field=models.ImageField(upload_to='image/%Y/%m/%d/cian', verbose_name='Фото объекта'),
        ),
        migrations.AlterField(
            model_name='flat_obj',
            name='client_tel',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='+79881234567', max_length=128, verbose_name='тел собственника'),
        ),
    ]
