# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_auto_20180220_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='stat_obj_crm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_nic', models.CharField(max_length=40, verbose_name='Риелтор login:')),
                ('auth_ful_name', models.CharField(default='1', max_length=60, verbose_name='Риелтор ФИО')),
                ('auth_group', models.CharField(default='1', max_length=25, verbose_name='отдел')),
                ('crm_calc', models.IntegerField(default=0, verbose_name='Кол-во обьектов в CRM')),
                ('cian_calc', models.IntegerField(default=0, verbose_name='Кол-во обьектов в CRM')),
            ],
            options={
                'verbose_name': 'Статистика по обьектам в ЦРМ',
                'verbose_name_plural': 'Статистика по обьектам в ЦРМ',
            },
        ),
    ]
