# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 12:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_stat_obj_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_obj',
            name='kadastr',
            field=models.CharField(blank=True, help_text='Необязательно к заполнению', max_length=20, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Кадастровый номер'),
        ),
    ]
