# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_auto_20180222_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_obj',
            name='kvart_numb',
            field=models.CharField(blank=True, default='', help_text='например: 11', max_length=5, verbose_name='Номер квартиры:'),
        ),
    ]
