# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_auto_20180223_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat_obj_crm',
            options={'verbose_name': 'Стат. по обьектам в ЦРМ', 'verbose_name_plural': 'Стат. по обьектам в ЦРМ'},
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='date_sozd',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='stat_obj_crm',
            name='crm_calc_week',
            field=models.IntegerField(default=0, verbose_name='Кол-во обьектов в CRM(за неделю)'),
        ),
        migrations.AddField(
            model_name='stat_obj_crm',
            name='date_sozd',
            field=models.DateField(auto_now=True, verbose_name='Дата создания:'),
        ),
    ]
