# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_auto_20180223_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_obj',
            name='date_sozd',
            field=models.DateField(blank=True, verbose_name='Дата создания'),
        ),
    ]
