# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-02 10:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_auto_20180228_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='budget',
            field=models.IntegerField(default=1000000, validators=[django.core.validators.MinValueValidator(100000)], verbose_name='Бюджет до:'),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='kanal',
            field=models.CharField(choices=[('Заявка с сайта', 'Заявка с сайта'), ('Заявка с сайта новостройка', 'Заявка с сайта новостройка'), ('Тел. звонок', 'Тел. звонок'), ('Домклик', 'Домклик')], default='', max_length=35, verbose_name='Канал привлечения'),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='nazv_novostr',
            field=models.CharField(default='', max_length=45, verbose_name='Название новостройки'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='date_sozd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания:'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='komnat',
            field=models.CharField(choices=[('Студия', 'Студия'), ('Однокомнатная', 'Однокомнатная'), ('Двухкомнатная', 'Двухкомнатная'), ('Трехкомнатная', 'Трехкомнатная'), ('Многокомнатная', 'Многокомнатная'), ('Неважно', 'Неважно'), ('Дом', 'Дом'), ('Участок', 'Участок'), ('Коммерция', 'Коммерция')], default='Неважно', max_length=25, verbose_name='Тип недвижимости(что ищет):'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='ploshad',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Желаемая площадь:'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='prim',
            field=models.CharField(max_length=150, verbose_name='Примечание:'),
        ),
    ]
