# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0053_auto_20180306_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='kanal',
            field=models.CharField(choices=[('Заявка с сайта', 'Заявка с сайта'), ('Заявка с сайта новостройка', 'Заявка с сайта новостройка'), ('Тел. звонок', 'Тел. звонок'), ('Домклик', 'Домклик'), ('Личный', 'Личный')], default='', max_length=35, verbose_name='Канал привлечения'),
        ),
    ]
