# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_auto_20180307_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile1',
            name='nach_otd',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3, verbose_name='Начальник отдела'),
        ),
    ]
