# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_auto_20180320_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reyt_sdelka_otd',
            name='kommisia',
            field=models.IntegerField(default=0, verbose_name='Коммисия'),
        ),
    ]
