# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0062_auto_20180326_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='otchet_nov',
            name='all_rielts',
            field=models.CharField(default='', max_length=250, verbose_name='все риелторы в сделк1е:'),
        ),
    ]
