# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-02 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0065_auto_20180330_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_obj',
            name='domclick_pub',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Опубликовать на Домклик'),
        ),
    ]
