# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0066_flat_obj_domclick_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_obj',
            name='balcony',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет'), ('2 балкона', '2 балкона'), ('2 лоджии', '2 лоджии')], default='нет', max_length=3, verbose_name='Балконы:'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='lift',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], default='нет', max_length=3, verbose_name='Лифт:'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='rubbish_chute',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], default='нет', max_length=3, verbose_name='Мусоропровод:'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='security',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], default='нет', max_length=3, verbose_name='Наличие охраны:'),
        ),
    ]
