# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_auto_20180403_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_obj',
            name='adress_utf',
            field=models.CharField(default='', help_text='например: Гагарина', max_length=270, verbose_name='Улица UTF:'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='allias',
            field=models.CharField(default='', max_length=250, verbose_name='Алиас'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='date_vigr_sait',
            field=models.DateField(auto_now=True, verbose_name='Дата выгрузки на сайт:'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='nazv',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Название обьекта'),
        ),
        migrations.AddField(
            model_name='userprofile1',
            name='joomla_usr_id',
            field=models.CharField(default='', max_length=10, verbose_name='ID пользователя в Joomla'),
        ),
    ]
