# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-03 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0069_auto_20180503_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachestvodomcl',
            name='vsego',
            field=models.IntegerField(default='', verbose_name='Всего обьектов'),
        ),
        migrations.AlterField(
            model_name='flat_obj',
            name='kredit',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ипотека СберБанк', 'Ипотека СберБанк'), ('Ипотека РоссельхозБанк', 'Ипотека РоссельхозБанк'), ('Ипотека ВТБ24', 'Ипотека ВТБ24'), ('Мат.капитал', 'Мат капитал'), ('Воен ипотека', 'Воен ипотека'), ('Рассрочка', 'Рассрочка'), ('Только наличные', 'Только наличными')], default='Ипотека СберБанк', max_length=104, verbose_name='Усл.Кредита'),
        ),
    ]
