# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_auto_20180515_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_obj',
            name='kadastr_pr',
            field=models.CharField(default='Нет', max_length=3),
        ),
    ]
