# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-31 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0075_auto_20180528_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otchet_nov',
            name='ot_kuda_kl',
            field=models.CharField(choices=[('Другое', 'Другое'), ('Avito', 'Avito'), ('Cian', 'Cian'), ('Сайт компании', 'Сайт компании'), ('По рекомендации', 'По рекомендации'), ('Домклик(Сбер)', 'Домклик(Сбер)'), ('Yandex Недвижимость', 'Yandex Недвижимость')], max_length=20, verbose_name='Канал привлечения клиента:'),
        ),
    ]
