# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0076_auto_20180531_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat_obj',
            options={'verbose_name': 'Все обьекты', 'verbose_name_plural': 'Все обьекты'},
        ),
        migrations.AlterModelOptions(
            name='flat_obj_gal',
            options={'verbose_name': 'Все обьекты галерея', 'verbose_name_plural': 'Все обьекты галерея'},
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='h_etagnost',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='n/a', max_length=3, verbose_name='Этажность:'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='h_infr',
            field=models.CharField(choices=[('Озеленение', 'Озеленение'), ('Детская площадка', 'Детская площадка'), ('Зона отдыха', 'Зона отдыха'), ('Парковка', 'Парковка'), ('Остановка', 'Остановка'), ('Школа', 'Школа'), ('Больница', 'Больница')], default='n/a', max_length=25, verbose_name='Инфраструктура:'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='h_isp_uch',
            field=models.CharField(choices=[('Поселений (ИЖС)', 'Поселений (ИЖС)'), ('Садовое некоммерческое товарищество', 'Садовое некоммерческое товарищество'), ('Земля промназначения', 'Земля промназначения'), ('ДНП', 'ДНП'), ('Размещение эллингов', 'Размещение эллингов')], default='n/a', max_length=25, verbose_name='Использование участка:'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='h_komnat',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='n/a', max_length=3, verbose_name='Комнат:'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='h_ploshad_uch',
            field=models.DecimalField(decimal_places=1, default='0', max_digits=4, verbose_name='Площадь участка'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='h_rast_more',
            field=models.IntegerField(default=0, verbose_name='Растояние до моря:'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='h_tip_doma',
            field=models.CharField(choices=[('Монолитный', 'Монолитный'), ('Блочный', 'Блочный'), ('Каркасно-монолитный', 'Каркасно-монолитный'), ('Кирпичный', 'Кирпичный'), ('Деревянный', 'Деревянный'), ('Панельный', 'Панельный')], default='n/a', max_length=25, verbose_name='Тип дома'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='h_vid_is_okon',
            field=models.CharField(choices=[('На горы и море', 'На горы и море'), ('На горы', 'На горы'), ('На море', 'На море'), ('Обычный', 'Обычный')], default='n/a', max_length=25, verbose_name='Вид из окон:'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='h_vid_prava',
            field=models.CharField(choices=[('Собственность', 'Собственность'), ('Аренда (49лет)', 'Аренда (49лет)'), ('Аренда (49лет)', 'Аренда (49лет)')], default='n/a', max_length=25, verbose_name='Вид права:'),
        ),
        migrations.AddField(
            model_name='flat_obj',
            name='type',
            field=models.CharField(choices=[('flat', 'flat'), ('house', 'house'), ('uchastok', 'uchastok'), ('komerc', 'komerc')], default='flat', max_length=25, verbose_name='Тип недвижимости'),
        ),
    ]
