# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-05 09:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0083_auto_20180629_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otchet_nov',
            name='otd_reelt10',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Отдел:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='otd_reelt2',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Отдел:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='otd_reelt3',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Отдел:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='otd_reelt4',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Отдел:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='otd_reelt5',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Отдел:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='otd_reelt6',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Отдел:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='otd_reelt7',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Отдел:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='otd_reelt8',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Отдел:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='otd_reelt9',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Отдел:'),
        ),
        migrations.AlterField(
            model_name='otchet_nov',
            name='rielt_proc1',
            field=models.IntegerField(blank=True, default=100, help_text='Обязательно к заполнению!', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Доля(%) риелтора №1 в сделке:'),
        ),
    ]
