# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0084_auto_20180705_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otchet_nov',
            name='pr_prosmotra_golovin',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Признак просмотра Головиным'),
        ),
    ]
