# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-13 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0086_auto_20180713_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_obj',
            name='prim',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
