# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-08 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0092_auto_20180807_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile1',
            name='vestum_count_ads',
            field=models.IntegerField(default=0, verbose_name='Кол-во обьявлений в Вестум:'),
        ),
    ]
