# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0093_userprofile1_vestum_count_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_obj',
            name='old_building_name',
            field=models.BooleanField(default=False, verbose_name='Да если дому больше 15 лет'),
        ),
        migrations.AlterField(
            model_name='flat_obj',
            name='building_name',
            field=models.CharField(blank=True, default='', help_text='ЖК Остров мечты, литер 2', max_length=150, verbose_name='Или название новостройки(до 15 лет) для Vestum'),
        ),
    ]
