# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-16 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0102_auto_20180816_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_obj',
            name='vestum_pub',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Публиковать на Вестум?'),
        ),
    ]
