# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-17 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0109_auto_20180817_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='prim',
            field=models.TextField(verbose_name='Примечание:'),
        ),
    ]
