# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-20 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0110_auto_20180817_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_obj',
            name='nov_nazv',
            field=models.CharField(default='', help_text='Для публикации в вестум. Если дому больше 15 лет то напишите Вторичка', max_length=150, verbose_name='Название новостройки:'),
        ),
    ]
