# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-20 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0111_flat_obj_nov_nazv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_obj',
            name='nov_nazv',
            field=models.CharField(blank=True, default='', help_text='Для публикации в вестум. Если дому больше 15 лет то напишите Вторичка', max_length=150, verbose_name='Название новостройки:'),
        ),
    ]
