# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-21 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0112_auto_20180820_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_obj',
            name='vestum_pub',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3, verbose_name='Публиковать на Вестум?'),
        ),
    ]
