# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0113_auto_20180821_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_obj',
            name='exclusiv',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], default='Нет', max_length=3, verbose_name='Эксклюзивные права на продажу'),
        ),
    ]
