# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0114_flat_obj_exclusiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_obj',
            name='exclusiv',
            field=models.CharField(choices=[('Нет', 'Нет'), ('Да', 'Да')], default='Нет', max_length=3, verbose_name='Эксклюзивные права на продажу:'),
        ),
    ]
