# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0119_auto_20180927_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_obj',
            name='date_vigr_sait',
            field=models.DateField(verbose_name='Дата выгрузки на сайт:'),
        ),
    ]
