# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-20 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='zvonok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Дата создания:', models.DateTimeField(auto_now=True)),
                ('tel', models.CharField(help_text='9881112233', max_length=10, verbose_name='Телефон')),
                ('client_name', models.CharField(blank=True, max_length=45, verbose_name='Имя клиента:')),
                ('prim', models.TextField(blank=True, verbose_name='Примечание')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Риелтор:')),
            ],
            options={
                'verbose_name': 'Звонки риелторам',
                'verbose_name_plural': 'Звонки риелторам',
            },
        ),
    ]
