# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-20 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zvonok',
            name='client_name',
            field=models.CharField(max_length=45, verbose_name='Имя клиента:'),
        ),
        migrations.AlterField(
            model_name='zvonok',
            name='prim',
            field=models.TextField(verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='zvonok',
            name='tel',
            field=models.IntegerField(help_text='9881112233', verbose_name='Телефон'),
        ),
    ]
