# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-20 12:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0004_auto_20180720_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zvonok',
            name='cena',
            field=models.IntegerField(default=800000, validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Бюджет до:'),
        ),
    ]
