# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-20 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0005_auto_20180720_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='zvonok',
            name='coment',
            field=models.TextField(blank=True, verbose_name='Коментарий по проделанной работе'),
        ),
        migrations.AddField(
            model_name='zvonok',
            name='prezvonit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Перезвонить: '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zvonok',
            name='prim',
            field=models.TextField(blank=True, verbose_name='Первичная информация'),
        ),
    ]
