# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-24 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0007_auto_20180724_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zvonok',
            name='prezvonit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 24, 12, 22, 38, 460014), verbose_name='Перезвонить: '),
        ),
    ]
