# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-24 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0008_auto_20180724_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zvonok',
            name='status_zvonka',
        ),
        migrations.AlterField(
            model_name='zvonok',
            name='prezvonit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 24, 15, 2, 21, 465474), verbose_name='Перезвонить: '),
        ),
    ]
