# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-24 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0009_auto_20180724_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='zvonok',
            name='status_zvonka',
            field=models.CharField(choices=[('Перезвонить', 'Перезвонить'), ('Недозвонился', 'Недозвонился'), ('В работе', 'В работе'), ('Архив', 'Архив'), ('В общем доступе', 'В общем доступе')], default='Перезвонить', max_length=55, verbose_name='Статус звонка'),
        ),
        migrations.AlterField(
            model_name='zvonok',
            name='prezvonit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 24, 15, 11, 10, 600700), verbose_name='Перезвонить: '),
        ),
    ]
