# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-24 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0011_auto_20180724_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zvonok',
            name='prezvonit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 24, 16, 27, 31, 257358), verbose_name='Перезвонить: '),
        ),
    ]
