# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-25 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0012_auto_20180724_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zvonok',
            name='prezvonit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 25, 14, 24, 8, 539815), verbose_name='Перезвонить: '),
        ),
        migrations.AlterField(
            model_name='zvonok',
            name='status_zvonka',
            field=models.CharField(choices=[('Перезвонить', 'Перезвонить'), ('Недозвонился', 'Недозвонился'), ('В работе', 'В работе'), ('Архив', 'Архив'), ('В общем доступе', 'В общем доступе')], max_length=55, verbose_name='Статус звонка'),
        ),
    ]
