# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-25 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0013_auto_20180725_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zvonok',
            name='Дата создания:',
        ),
        migrations.AddField(
            model_name='zvonok',
            name='date_sozd',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания:'),
        ),
        migrations.AlterField(
            model_name='zvonok',
            name='prezvonit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 25, 15, 11, 40, 612235), verbose_name='Перезвонить: '),
        ),
    ]
