# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-30 10:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0015_auto_20180727_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zvonok',
            name='prezvonit',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 30, 13, 32, 41, 441353), verbose_name='Перезвонить: '),
        ),
    ]
