# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-30 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0015_auto_20180725_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zvonok',
            name='prezvonit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 30, 13, 36, 16, 983546), verbose_name='Перезвонить: '),
        ),
    ]
