# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-31 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0019_auto_20180731_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zvonok',
            name='status_zvonka',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Перезвонить', 'Перезвонить'), ('Недозвонился', 'Недозвонился'), ('В работе', 'В работе'), ('Архив', 'Архив'), ('В общем доступе', 'В общем доступе')], default='Новый', max_length=55, verbose_name='Статус звонка'),
        ),
    ]
