# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-01 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0021_auto_20180731_1458'),
        ('zvonki', '0016_auto_20180730_1336'),
    ]

    operations = [
    ]
