# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-01 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvonki', '0022_merge_20180801_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zvonok',
            name='prezvonit',
            field=models.DateTimeField(blank=True, verbose_name='Перезвонить: '),
        ),
    ]
